name: Goreleaser

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    tags: ["v*"]

jobs:
  tagger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create tag
        id: create
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request' && github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/')
        with:
          github-token: ${{ github.token }}
          script: |
            const tag = context.payload.pull_request.head.ref.replace("release/", "v")
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/" + tag,
              })
            } catch {
            }
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/" + tag,
              sha: context.payload.pull_request.merge_commit_sha,
            })
            return tag
          result-encoding: string

      - name: Get pushed tag
        id: push
        if: github.event_name == 'push'
        run: echo "result=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: combine tags
        id: combined
        run: echo "tag=${PUSHED_TAG}${CREATED_TAG}" >> $GITHUB_OUTPUT
        env:
          CREATED_TAG: ${{ steps.tag.outputs.result }}
          PUSHED_TAG: ${{ steps.push.outputs.result }}
    outputs:
      tag: ${{ steps.combined.outputs.tag }}

  generate-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to commit changes
    needs:
      - tagger
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # ref: main
          ref: changie # TODO: remove

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download changie
        run: go install github.com/miniscruff/changie@v1

      - name: Generate release changelog
        run: changie batch $TAG
        env:
          TAG: ${{ needs.tagger.outputs.tag }}

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: .changes/${{ needs.tagger.outputs.tag }}.md

      - name: Merge changelog
        run: changie merge

      - name: Commit changelog changes
        uses: EndBug/add-and-commit@v9
        # TODO: uncomment
        # if: "!contains(needs.tagger.outputs.tag, 'rc')"
        with:
          default_author: github_actions
          message: "chore: update changelog"
          add: "CHANGELOG.md .changes"

  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write # releases are in `contents`
      issues: write # for closing milestones
      packages: write
    needs:
      - tagger
      - generate-changelog
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.tagger.outputs.tag }}

      # - name: Setup QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download changelog artifact
        uses: actions/download-artifact@v3
        with:
          name: changelog

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --skip-docker --skip-validate --rm-dist --release-notes .changes/${{ needs.tagger.outputs.tag }}.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.CR_PAT }}
          TELEGRAM_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Generate schema.json
        run: ./dist/helmwave schema > schema.json

      - name: Upload schema.json
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "schema.json"
          update_latest_release: true

  docs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    needs:
      - tagger
    steps:
      - name: Trigger helmwave/docs workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: "docs",
              workflow_id: "generate-new-version.yml",
              ref: "main",
              inputs: {
                tag: process.env.GITHUB_TAG,
              },
            })
        env:
          GITHUB_TAG: ${{ needs.tagger.outputs.tag }}
